/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResponsiveCheckRouteImport } from './routes/responsive-check'
import { Route as ReferenceRouteImport } from './routes/reference'
import { Route as OptimizationMethodsRouteImport } from './routes/optimization-methods'
import { Route as KnowledgeFeedbackRouteImport } from './routes/knowledge-feedback'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as DebugRouteImport } from './routes/debug'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'

const ResponsiveCheckRoute = ResponsiveCheckRouteImport.update({
  id: '/responsive-check',
  path: '/responsive-check',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceRoute = ReferenceRouteImport.update({
  id: '/reference',
  path: '/reference',
  getParentRoute: () => rootRouteImport,
} as any)
const OptimizationMethodsRoute = OptimizationMethodsRouteImport.update({
  id: '/optimization-methods',
  path: '/optimization-methods',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeFeedbackRoute = KnowledgeFeedbackRouteImport.update({
  id: '/knowledge-feedback',
  path: '/knowledge-feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugRoute = DebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/debug': typeof DebugRoute
  '/knowledge': typeof KnowledgeRoute
  '/knowledge-feedback': typeof KnowledgeFeedbackRoute
  '/optimization-methods': typeof OptimizationMethodsRoute
  '/reference': typeof ReferenceRoute
  '/responsive-check': typeof ResponsiveCheckRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/debug': typeof DebugRoute
  '/knowledge': typeof KnowledgeRoute
  '/knowledge-feedback': typeof KnowledgeFeedbackRoute
  '/optimization-methods': typeof OptimizationMethodsRoute
  '/reference': typeof ReferenceRoute
  '/responsive-check': typeof ResponsiveCheckRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/debug': typeof DebugRoute
  '/knowledge': typeof KnowledgeRoute
  '/knowledge-feedback': typeof KnowledgeFeedbackRoute
  '/optimization-methods': typeof OptimizationMethodsRoute
  '/reference': typeof ReferenceRoute
  '/responsive-check': typeof ResponsiveCheckRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/debug'
    | '/knowledge'
    | '/knowledge-feedback'
    | '/optimization-methods'
    | '/reference'
    | '/responsive-check'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/debug'
    | '/knowledge'
    | '/knowledge-feedback'
    | '/optimization-methods'
    | '/reference'
    | '/responsive-check'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/debug'
    | '/knowledge'
    | '/knowledge-feedback'
    | '/optimization-methods'
    | '/reference'
    | '/responsive-check'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DebugRoute: typeof DebugRoute
  KnowledgeRoute: typeof KnowledgeRoute
  KnowledgeFeedbackRoute: typeof KnowledgeFeedbackRoute
  OptimizationMethodsRoute: typeof OptimizationMethodsRoute
  ReferenceRoute: typeof ReferenceRoute
  ResponsiveCheckRoute: typeof ResponsiveCheckRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/responsive-check': {
      id: '/responsive-check'
      path: '/responsive-check'
      fullPath: '/responsive-check'
      preLoaderRoute: typeof ResponsiveCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference': {
      id: '/reference'
      path: '/reference'
      fullPath: '/reference'
      preLoaderRoute: typeof ReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/optimization-methods': {
      id: '/optimization-methods'
      path: '/optimization-methods'
      fullPath: '/optimization-methods'
      preLoaderRoute: typeof OptimizationMethodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-feedback': {
      id: '/knowledge-feedback'
      path: '/knowledge-feedback'
      fullPath: '/knowledge-feedback'
      preLoaderRoute: typeof KnowledgeFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DebugRoute: DebugRoute,
  KnowledgeRoute: KnowledgeRoute,
  KnowledgeFeedbackRoute: KnowledgeFeedbackRoute,
  OptimizationMethodsRoute: OptimizationMethodsRoute,
  ReferenceRoute: ReferenceRoute,
  ResponsiveCheckRoute: ResponsiveCheckRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
